name: DevSecOps Security Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    name: Run Security Scans
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Semgrep SAST scan
        uses: docker://returntocorp/semgrep
        with:
          args: semgrep --config=p/owasp-top-ten --json --output=semgrep_results.json

      - name: Upload Semgrep results
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: semgrep_results.json

          out: "./reports"
